### ISSUE TITLE
Make it easy to add slash menu items

### ISSUE THREAD

**Issue by yassinebridi** [YousefED/BlockNote#102]
Right now slash menu items are hardcoded, it would be really cool for it to be configurable.

I believe it's already doable if the `SlashMenuExtension` is exported from `@blocknote/core`.

and just add it to the extensions like this:
```ts
extensions: [
  SlashMenuExtension.configure({
    slashMenuFactory: ReactSlashMenuFactory,
  }),
],
```
But again you would have more control over the keyboard shortcut and icons, etc..

**Comment by YousefED** [comment]
Hi @yassinebridi !

This is now possible. See https://www.blocknotejs.org/docs/slash-menu.

Also, we just released the website with docs. Feedback welcome!
