### ISSUE TITLE
Bug: keep styles on copy / paste

### ISSUE THREAD

**Issue by YousefED** [YousefED/BlockNote#40]
See https://twitter.com/steventey/status/1567956854801833984

**Comment by imrishabh18** [comment]
Hey @YousefED, I came across your tweet and really liked the project. So, I would like to contribute to this Project, I was exploring the project structure but it would be helpful if you can point me to the direction where I can resolve this issue.

**Comment by richmengsix** [comment]
I submitted a PR for this issue at https://github.com/YousefED/BlockNote/pull/41. Please take a look whenever you get a chance @YousefED :)
