### ISSUE TITLE
Numbering of nested ordered lists is inherited from parent list's numbering

### ISSUE THREAD

**Issue by brandondrew** [YousefED/BlockNote#62]
When nesting an ordered list inside another one, the first item in the nested list should not have the same numbering as if it were at the level of its parent.

For example, this is correct (not because GitHub's markdown editor correctly number it, but because the number is editable and I forced it to be correct):

1. this should be "1"
2. this should be "2"
  a. this should NOT be "3"

In the case of BlockNote, it is neither automatically numbered correctly _nor_ is it possible for the user to force it to be correct.
![BlockNote](https://user-images.githubusercontent.com/9854/201446185-3fe43f7d-7fcc-4167-862a-5bc1e1f9fde2.png)

**Comment by YousefED** [comment]
Thanks! fixed in #42

**Comment by brandondrew** [comment]
wow that was fast! 👏🏻👏🏻👏🏻
