### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by Learces** [YousefED/BlockNote#96]

**Comment by YousefED** [comment]
Hi @Learces . Just added a basic overview here, showing what we're mostly working on atm: https://github.com/users/YousefED/projects/2/views/1

**Comment by aarkue** [comment]
> Hi @Learces . Just added a basic overview here, showing what we're mostly working on atm: https://github.com/users/YousefED/projects/2/views/1
@YousefED 
Hi, I am also interested in this project.
The link does not seem to work for me (shows 404).
Could you double-check if it is correct? Thanks!

**Comment by YousefED** [comment]
Fixed! @aarkue @Learces , now public

**Comment by tsl1127** [comment]
The link does not seem to work again(shows 404)

**Comment by YousefED** [comment]
Try this one! https://github.com/orgs/TypeCellOS/projects/1/
